services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '9201:3000'
    environment: # Added environment variables for better configuration
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/nest_db

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

volumes:
  postgres_data:
